#!/bin/bash
python3 set_password.py $PASSWORD
export PYTHONPATH=/notebooks
jupyter notebook \
    --allow-root \
    --NotebookApp.port=8888 \
    --NotebookApp.open_browser=False \
    --NotebookApp.ip='0.0.0.0' \
    --NotebookApp.notebook_dir='/notebooks' \
    --IPKernelApp.pylab='inline'
