#!/bin/bash
export PYTHONPATH=/notebooks
jupyter notebook \
    --NotebookApp.port=8888 \
    --NotebookApp.open_browser=False \
    --NotebookApp.ip='0.0.0.0' \
    --NotebookApp.notebook_dir='/notebooks' \
    --IPKernelApp.pylab='inline' 
